#
# ~/.bashrc
#

export PATH=$PATH:/home/church/.local/bin

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

alias ls='ls --color=auto'
alias grep='grep --color=auto'
PS1='[\u@\h \W]\$ '


# eval "$(starship init bash)"

export PIPENV_VENV_IN_PROJECT=1
