# Helpers are user-defined functions that can be executed inside templates.
# This section is optional.
[helpers]
# color_hex2rgb = "dotter_settings/helpers/color_hex2rgb.rhai"

# A package contains two sections - "files" and "variables".
# Both of those sections are optional - you can have only one if you want.

# The 'files' section is a mapping between the path of the file relative to
# the repository root and its location in the filesystem (where the program
# expects it)
# In this case, say your repository is at `~/.dotfiles`, it will map
# `~/.dotfiles/zsh/zprofile` to `~/.zprofile`,
# and `~/.dotfiles/zshrc` to `~/.zshrc`
# To clarify, folders in the repository don't have to correspond to packages.
# On Windows, '~' is expanded to 'C:\Users\<USERNAME>\'

[autorandr.files]
# "config/autorandr/docked/config" = "~/.config/autorandr/docked/config"
# "config/autorandr/docked/setup" = "~/.config/autorandr/docked/setup"
# "config/autorandr/mobile/config" = "~/.config/autorandr/mobile/config"
# "config/autorandr/mobile/setup" = "~/.config/autorandr/mobile/setup"

[i3.files]
"config/i3/config" = "~/.config/i3/config"
"config/i3status/config" = "~/.config/i3status/config"
"config/xfce4/xfconf/xfce-perchannel-xml/xfce4-power-manager.xml" = {target = "~/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-power-manager.xml", type = "symbolic"}

[user.files]

[bash.files]
"config/bashrc" = "~/.bashrc"

[X11.files]
"etc/X11/xorg.conf.d/00-keyboard.conf" = { target = "/etc/X11/xorg.conf.d/00-keyboard.conf", type = "symbolic", owner = "root" }
"etc/X11/xorg.conf.d/30-touchpad.conf" = { target = "/etc/X11/xorg.conf.d/30-touchpad.conf", type = "symbolic", owner = "root" }

[xmonad.files]
"config/xmonad" = { target = "~/.config/xmonad", type = "symbolic" }
"home/xmobarrc" = "~/.xmobarrc"
"home/stalonetrayrc" = "~/.stalonetrayrc"

[TouchOSC.files]
"config/TouchOSC/ChurchService.tosc" = { target = "~/.config/TouchOSC/ChurchService.tosc", type = "symbolic"}

[openLPOSCControl.files]
"usr/share/OpenLPOSCControl/Pipfile" = { target = "/usr/share/OpenLPOSCControl/Pipfile", type = "template", owner = "root"}
"usr/share/OpenLPOSCControl/Pipfile.lock" = { target = "/usr/share/OpenLPOSCControl/Pipfile.lock", type = "template", owner = "root"}
"local/bin/OpenLPOSCControl.sh" = { target = "/usr/local/bin/OpenLPOSCControl", type = "symbolic", owner = "root"}
"etc/systemd/system/OpenLPOSCControl.service" = { target = "/etc/systemd/system/OpenLPOSCControl.service", type = "symbolic", owner = "root"}

[AV.files]
"local/bin/setupAV.sh" = { target = "/usr/local/bin/setupAV", type = "symbolic", owner = "root"}
